# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('ministry', models.CharField(choices=[('', 'Please select which ministry you want to donate to'), ('Men', 'Men Fellowship'), ('Women', 'Women Fellowship'), ('Children', 'Children Fellowship'), ('Youth', 'Youth Fellowship')], max_length=10)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Youth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=500)),
            ],
        ),
    ]
