# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ministry',
            field=models.CharField(choices=[('', 'Please select which ministry you want to donate to'), ('Men', 'Men Fellowship'), ('Women', 'Women Fellowship'), ('Children', 'Children Fellowship'), ('Youth', 'Youth Fellowship')], max_length=10),
        ),
    ]
