# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymn', '0002_auto_20160910_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='hymn',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
