# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hymn', '0003_hymn_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hymn',
            name='slug',
        ),
    ]
