# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
