# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20161029_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
    ]
