# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20161029_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='categorys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='resources.Tag'),
        ),
    ]
